import React from 'react'
import { Document, Page, Text, View, StyleSheet, Svg, Path } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#333' },
  // Cover
  coverPage: { padding: 40, display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' },
  coverBrand: { fontSize: 14, fontWeight: 'bold', letterSpacing: 4, color: '#111', marginBottom: 8 },
  coverAccent: { color: '#2563eb' },
  coverTitle: { fontSize: 32, fontWeight: 'bold', color: '#111', marginBottom: 8, textAlign: 'center' },
  coverType: { fontSize: 14, color: '#666', marginBottom: 24, textTransform: 'uppercase', letterSpacing: 2 },
  coverDate: { fontSize: 10, color: '#999' },
  coverFooter: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#bbb' },
  // Section
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#111', marginBottom: 12, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: '#e8e8e4' },
  sectionLabel: { fontSize: 8, color: '#999', textTransform: 'uppercase', letterSpacing: 2, marginBottom: 4 },
  // Tech grid
  techGrid: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  techCard: { width: '30%', padding: 8, borderWidth: 1, borderColor: '#e8e8e4', borderRadius: 6, marginBottom: 8, borderLeftWidth: 3 },
  techName: { fontSize: 10, fontWeight: 'bold', color: '#111', marginBottom: 2 },
  techCategory: { fontSize: 7, color: '#999', textTransform: 'uppercase', letterSpacing: 0.5 },
  techDesc: { fontSize: 8, color: '#666', marginTop: 4, lineHeight: 1.4 },
  // Connections
  connRow: { display: 'flex', flexDirection: 'row', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  connCell: { flex: 1, fontSize: 9 },
  connHeader: { flex: 1, fontSize: 8, fontWeight: 'bold', color: '#999', textTransform: 'uppercase', letterSpacing: 1 },
})

type TechInfo = {
  id: string
  name: string
  category: string
  color: string
  description: string
}

type Connection = {
  sourceName: string
  targetName: string
}

type Props = {
  projectName: string
  projectType: string
  userName: string
  date: string
  technologies: TechInfo[]
  connections: Connection[]
  categorizedTechs: Record<string, TechInfo[]>
}

export function ProjectPdfDocument({ projectName, projectType, userName, date, technologies, connections, categorizedTechs }: Props) {
  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <View style={{ alignItems: 'center', marginTop: 200 }}>
          <Text style={styles.coverBrand}>
            CX<Text style={styles.coverAccent}>M</Text>
          </Text>
          <Text style={{ fontSize: 10, color: '#999', marginBottom: 60 }}>Project Builder</Text>
          <Text style={styles.coverTitle}>{projectName}</Text>
          <Text style={styles.coverType}>{projectType} Architecture</Text>
          <Text style={styles.coverDate}>Prepared for {userName} · {date}</Text>
        </View>
        <Text style={styles.coverFooter}>Generated by CXM Project Builder · cxm.nz</Text>
      </Page>

      {/* Technology Stack */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionLabel}>Technology Stack</Text>
        <Text style={styles.sectionTitle}>
          {technologies.length} Technologies · {Object.keys(categorizedTechs).length} Categories
        </Text>

        {Object.entries(categorizedTechs).map(([category, techs]) => (
          <View key={category} style={{ marginBottom: 16 }}>
            <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#2563eb', marginBottom: 6 }}>{category}</Text>
            <View style={styles.techGrid}>
              {techs.map(tech => (
                <View key={tech.id} style={[styles.techCard, { borderLeftColor: tech.color || '#ddd' }]}>
                  <Text style={styles.techName}>{tech.name}</Text>
                  <Text style={styles.techCategory}>{tech.category}</Text>
                  {tech.description && <Text style={styles.techDesc}>{tech.description}</Text>}
                </View>
              ))}
            </View>
          </View>
        ))}
      </Page>

      {/* Connections */}
      {connections.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionLabel}>Architecture</Text>
          <Text style={styles.sectionTitle}>
            {connections.length} Connections
          </Text>

          <View style={styles.connRow}>
            <Text style={styles.connHeader}>From</Text>
            <Text style={styles.connHeader}>To</Text>
          </View>

          {connections.map((conn, i) => (
            <View key={i} style={styles.connRow}>
              <Text style={styles.connCell}>{conn.sourceName}</Text>
              <Text style={styles.connCell}>{conn.targetName}</Text>
            </View>
          ))}
        </Page>
      )}
    </Document>
  )
}
