import { neon } from '@neondatabase/serverless'
import { config } from 'dotenv'
config({ path: '.env.local' })

const DATA: { name: string; categories: string[]; description: string; url: string }[] = [
  { name: "Algolia", categories: ["Search", "API"], description: "Hosted search-as-a-service platform with real-time indexing", url: "https://algolia.com" },
  { name: "Elasticsearch", categories: ["Search", "Database", "Analytics"], description: "Distributed search and analytics engine built on Apache Lucene", url: "https://elastic.co" },
  { name: "Meilisearch", categories: ["Search", "API"], description: "Open-source, fast, typo-tolerant search engine", url: "https://meilisearch.com" },
  { name: "Typesense", categories: ["Search", "API"], description: "Open-source, typo-tolerant search engine optimized for speed", url: "https://typesense.org" },
  { name: "VS Code", categories: ["Code Editor"], description: "Free, extensible source code editor by Microsoft", url: "https://code.visualstudio.com" },
  { name: "JetBrains", categories: ["Code Editor"], description: "Suite of professional IDEs for multiple languages", url: "https://jetbrains.com" },
  { name: "Neovim", categories: ["Code Editor"], description: "Hyperextensible Vim-based terminal text editor", url: "https://neovim.io" },
  { name: "Cursor", categories: ["Code Editor", "AI Tools"], description: "AI-native code editor built on VS Code", url: "https://cursor.com" },
  { name: "TypeScript", categories: ["Language"], description: "Typed superset of JavaScript that compiles to plain JS", url: "https://typescriptlang.org" },
  { name: "JavaScript", categories: ["Language"], description: "Dynamic scripting language for web browsers and server-side runtimes", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
  { name: "Python", categories: ["Language"], description: "General-purpose, high-level programming language", url: "https://python.org" },
  { name: "Rust", categories: ["Language"], description: "Systems programming language focused on safety and performance", url: "https://rust-lang.org" },
  { name: "Go", categories: ["Language"], description: "Statically typed, compiled language by Google for scalable systems", url: "https://go.dev" },
  { name: "Java", categories: ["Language"], description: "Object-oriented, platform-independent programming language", url: "https://java.com" },
  { name: "C#", categories: ["Language"], description: "Object-oriented language by Microsoft for the .NET platform", url: "https://learn.microsoft.com/en-us/dotnet/csharp/" },
  { name: "PHP", categories: ["Language"], description: "Server-side scripting language widely used for web development", url: "https://php.net" },
  { name: "Ruby", categories: ["Language"], description: "Dynamic, object-oriented scripting language focused on simplicity", url: "https://ruby-lang.org" },
  { name: "Swift", categories: ["Language"], description: "Compiled language by Apple for iOS, macOS, and server-side development", url: "https://swift.org" },
  { name: "Kotlin", categories: ["Language"], description: "Modern JVM language by JetBrains, official for Android development", url: "https://kotlinlang.org" },
  { name: "Dart", categories: ["Language"], description: "Client-optimized language by Google, powers Flutter", url: "https://dart.dev" },
  { name: "HubSpot", categories: ["Marketing", "Email", "CMS", "Analytics"], description: "Inbound marketing, CRM, and CMS platform", url: "https://hubspot.com" },
  { name: "Mailchimp", categories: ["Marketing", "Email"], description: "Email marketing and automation platform", url: "https://mailchimp.com" },
  { name: "Google Ads", categories: ["Marketing"], description: "Online advertising platform for search and display ads", url: "https://ads.google.com" },
  { name: "Meta Ads", categories: ["Marketing"], description: "Advertising platform for Facebook, Instagram, and Messenger", url: "https://business.facebook.com" },
  { name: "Optimizely", categories: ["Personalisation", "Testing", "Analytics"], description: "Digital experience and A/B testing optimization platform", url: "https://optimizely.com" },
  { name: "Cloudflare", categories: ["CDN", "Security", "Hosting"], description: "CDN, DDoS protection, DNS, and edge compute platform", url: "https://cloudflare.com" },
  { name: "Fastly", categories: ["CDN", "Security"], description: "Edge cloud platform with programmable CDN and security", url: "https://fastly.com" },
  { name: "Akamai", categories: ["CDN", "Security"], description: "Global CDN and cloud security provider", url: "https://akamai.com" },
  { name: "Vercel", categories: ["Hosting", "CDN"], description: "Frontend cloud platform optimized for Next.js and frameworks", url: "https://vercel.com" },
  { name: "Netlify", categories: ["Hosting", "CDN"], description: "Platform for deploying and hosting modern web applications", url: "https://netlify.com" },
  { name: "AWS", categories: ["Hosting", "CDN", "Database", "Containerisation"], description: "Comprehensive cloud computing platform by Amazon", url: "https://aws.amazon.com" },
  { name: "Google Cloud", categories: ["Hosting", "CDN", "Database", "Containerisation"], description: "Cloud computing services and infrastructure by Google", url: "https://cloud.google.com" },
  { name: "Azure", categories: ["Hosting", "CDN", "Database", "Containerisation"], description: "Cloud computing platform by Microsoft", url: "https://azure.microsoft.com" },
  { name: "Railway", categories: ["Hosting"], description: "Cloud platform for deploying apps and databases with minimal config", url: "https://railway.app" },
  { name: "Render", categories: ["Hosting"], description: "Cloud platform for hosting web apps, APIs, and databases", url: "https://render.com" },
  { name: "Fly.io", categories: ["Hosting"], description: "Platform for running full-stack apps close to users globally", url: "https://fly.io" },
  { name: "DigitalOcean", categories: ["Hosting"], description: "Cloud infrastructure provider for developers and small businesses", url: "https://digitalocean.com" },
  { name: "Heroku", categories: ["Hosting"], description: "Platform-as-a-service for building and running cloud applications", url: "https://heroku.com" },
  { name: "Shopify", categories: ["Ecommerce", "Hosting"], description: "Hosted ecommerce platform for online stores", url: "https://shopify.com" },
  { name: "BigCommerce", categories: ["Ecommerce"], description: "SaaS ecommerce platform for online retail", url: "https://bigcommerce.com" },
  { name: "Magento", categories: ["Ecommerce"], description: "Open-source ecommerce platform by Adobe", url: "https://business.adobe.com/products/magento/magento-commerce.html" },
  { name: "WooCommerce", categories: ["Ecommerce"], description: "Open-source ecommerce plugin for WordPress", url: "https://woocommerce.com" },
  { name: "Medusa", categories: ["Ecommerce"], description: "Open-source headless commerce engine built with Node.js", url: "https://medusajs.com" },
  { name: "PostgreSQL", categories: ["Database"], description: "Advanced open-source relational database system", url: "https://postgresql.org" },
  { name: "MySQL", categories: ["Database"], description: "Widely used open-source relational database", url: "https://mysql.com" },
  { name: "MongoDB", categories: ["Database"], description: "Document-oriented NoSQL database", url: "https://mongodb.com" },
  { name: "Redis", categories: ["Database", "CDN"], description: "In-memory data store used for caching, queues, and pub/sub", url: "https://redis.io" },
  { name: "Neon", categories: ["Database", "Hosting"], description: "Serverless PostgreSQL with branching and autoscaling", url: "https://neon.tech" },
  { name: "PlanetScale", categories: ["Database", "Hosting"], description: "Serverless MySQL platform built on Vitess", url: "https://planetscale.com" },
  { name: "Supabase", categories: ["Database", "Authentication", "Hosting", "API"], description: "Open-source Firebase alternative with Postgres, auth, and realtime", url: "https://supabase.com" },
  { name: "Turso", categories: ["Database"], description: "Edge-hosted distributed database built on libSQL", url: "https://turso.tech" },
  { name: "SQLite", categories: ["Database"], description: "Lightweight, file-based embedded relational database", url: "https://sqlite.org" },
  { name: "CockroachDB", categories: ["Database"], description: "Distributed SQL database designed for global scalability", url: "https://cockroachlabs.com" },
  { name: "DynamoDB", categories: ["Database"], description: "Fully managed NoSQL key-value database by AWS", url: "https://aws.amazon.com/dynamodb/" },
  { name: "Claude", categories: ["AI Tools"], description: "AI assistant and large language model by Anthropic", url: "https://anthropic.com" },
  { name: "ChatGPT", categories: ["AI Tools"], description: "Conversational AI assistant by OpenAI", url: "https://openai.com/chatgpt" },
  { name: "GitHub Copilot", categories: ["AI Tools", "Code Editor"], description: "AI pair programmer that suggests code in your editor", url: "https://github.com/features/copilot" },
  { name: "Google Gemini", categories: ["AI Tools"], description: "Multimodal AI model and assistant by Google", url: "https://gemini.google.com" },
  { name: "GitHub", categories: ["Repository", "CI/CD", "Collaboration"], description: "Code hosting, version control, and collaboration platform", url: "https://github.com" },
  { name: "GitLab", categories: ["Repository", "CI/CD", "Collaboration"], description: "DevOps platform with Git hosting, CI/CD, and project management", url: "https://gitlab.com" },
  { name: "Bitbucket", categories: ["Repository", "CI/CD"], description: "Git repository hosting by Atlassian with built-in CI/CD", url: "https://bitbucket.org" },
  { name: "Azure DevOps", categories: ["Repository", "CI/CD", "Collaboration"], description: "Microsoft DevOps suite with repos, pipelines, and boards", url: "https://azure.microsoft.com/en-us/products/devops" },
  { name: "VMware", categories: ["Virtualisation"], description: "Enterprise virtualization and cloud infrastructure platform", url: "https://vmware.com" },
  { name: "Proxmox", categories: ["Virtualisation", "Containerisation"], description: "Open-source server virtualization and container management platform", url: "https://proxmox.com" },
  { name: "VirtualBox", categories: ["Virtualisation"], description: "Free, cross-platform desktop virtualization by Oracle", url: "https://virtualbox.org" },
  { name: "Docker", categories: ["Containerisation"], description: "Platform for building and running containerized applications", url: "https://docker.com" },
  { name: "Kubernetes", categories: ["Containerisation"], description: "Open-source container orchestration system", url: "https://kubernetes.io" },
  { name: "Podman", categories: ["Containerisation"], description: "Daemonless container engine compatible with Docker", url: "https://podman.io" },
  { name: "containerd", categories: ["Containerisation"], description: "Industry-standard container runtime", url: "https://containerd.io" },
  { name: "Rancher", categories: ["Containerisation"], description: "Multi-cluster Kubernetes management platform", url: "https://rancher.com" },
  { name: "Sitecore", categories: ["CMS", "Personalisation"], description: "Enterprise .NET CMS with personalization and marketing features", url: "https://sitecore.com" },
  { name: "Contentful", categories: ["CMS", "API"], description: "Headless CMS with API-first content management", url: "https://contentful.com" },
  { name: "Sanity", categories: ["CMS", "API"], description: "Headless CMS with real-time collaboration and structured content", url: "https://sanity.io" },
  { name: "Strapi", categories: ["CMS", "API"], description: "Open-source headless CMS built with Node.js", url: "https://strapi.io" },
  { name: "WordPress", categories: ["CMS"], description: "Open-source CMS powering a large share of the web", url: "https://wordpress.org" },
  { name: "Storyblok", categories: ["CMS", "API"], description: "Headless CMS with a visual editor and component-based approach", url: "https://storyblok.com" },
  { name: "Prismic", categories: ["CMS", "API"], description: "Headless CMS with a slice-based content modeling system", url: "https://prismic.io" },
  { name: "Directus", categories: ["CMS", "API", "Database"], description: "Open-source data platform and headless CMS wrapping any SQL database", url: "https://directus.io" },
  { name: "Ghost", categories: ["CMS"], description: "Open-source publishing platform for blogs and newsletters", url: "https://ghost.org" },
  { name: "Drupal", categories: ["CMS"], description: "Open-source CMS for complex, content-rich websites", url: "https://drupal.org" },
  { name: "Keystone", categories: ["CMS", "API"], description: "Open-source headless CMS and GraphQL API framework for Node.js", url: "https://keystonejs.com" },
  { name: "React", categories: ["Frontend Framework"], description: "Component-based UI library by Meta for building interfaces", url: "https://react.dev" },
  { name: "Vue.js", categories: ["Frontend Framework"], description: "Progressive JavaScript framework for building UIs", url: "https://vuejs.org" },
  { name: "Angular", categories: ["Frontend Framework"], description: "TypeScript-based web application framework by Google", url: "https://angular.dev" },
  { name: "Svelte", categories: ["Frontend Framework"], description: "Compile-time UI framework that generates minimal JavaScript", url: "https://svelte.dev" },
  { name: "SolidJS", categories: ["Frontend Framework"], description: "Reactive UI library with fine-grained reactivity and no virtual DOM", url: "https://solidjs.com" },
  { name: "Astro", categories: ["Frontend Framework"], description: "Content-focused web framework with partial hydration", url: "https://astro.build" },
  { name: "Next.js", categories: ["Frontend Framework"], description: "React framework with SSR, SSG, and API routes by Vercel", url: "https://nextjs.org" },
  { name: "Nuxt.js", categories: ["Frontend Framework"], description: "Vue.js framework with SSR, SSG, and file-based routing", url: "https://nuxt.com" },
  { name: "Remix", categories: ["Frontend Framework"], description: "Full-stack React framework focused on web standards", url: "https://remix.run" },
  { name: "Gatsby", categories: ["Frontend Framework"], description: "React-based static site generator with GraphQL data layer", url: "https://gatsbyjs.com" },
  { name: "htmx", categories: ["Frontend Framework"], description: "Lightweight library for HTML-driven interactivity via attributes", url: "https://htmx.org" },
  { name: "Flutter", categories: ["Frontend Framework"], description: "Cross-platform UI toolkit by Google using Dart", url: "https://flutter.dev" },
  { name: "React Native", categories: ["Frontend Framework"], description: "Framework for building native mobile apps with React", url: "https://reactnative.dev" },
  { name: "Electron", categories: ["Frontend Framework"], description: "Framework for building cross-platform desktop apps with web tech", url: "https://electronjs.org" },
  { name: "Tauri", categories: ["Frontend Framework"], description: "Lightweight framework for cross-platform desktop apps using Rust", url: "https://tauri.app" },
  { name: "Tailwind CSS", categories: ["CSS Framework"], description: "Utility-first CSS framework for rapid UI development", url: "https://tailwindcss.com" },
  { name: "Bootstrap", categories: ["CSS Framework"], description: "Popular component-based CSS framework with responsive grid", url: "https://getbootstrap.com" },
  { name: "Chakra UI", categories: ["CSS Framework"], description: "Accessible React component library with composable styling", url: "https://chakra-ui.com" },
  { name: "Material UI", categories: ["CSS Framework"], description: "React component library implementing Google's Material Design", url: "https://mui.com" },
  { name: "Radix UI", categories: ["CSS Framework"], description: "Unstyled, accessible React UI primitives", url: "https://radix-ui.com" },
  { name: "shadcn/ui", categories: ["CSS Framework"], description: "Copy-paste React components built on Radix UI and Tailwind CSS", url: "https://ui.shadcn.com" },
  { name: "Sass", categories: ["CSS Framework"], description: "CSS preprocessor with variables, nesting, and mixins", url: "https://sass-lang.com" },
  { name: "styled-components", categories: ["CSS Framework"], description: "CSS-in-JS library for scoped styles in React components", url: "https://styled-components.com" },
  { name: "GraphQL", categories: ["API"], description: "Query language and runtime for APIs with typed schemas", url: "https://graphql.org" },
  { name: "tRPC", categories: ["API"], description: "End-to-end type-safe API layer for TypeScript apps", url: "https://trpc.io" },
  { name: "OpenAPI / Swagger", categories: ["API"], description: "Specification and tooling for describing RESTful APIs", url: "https://swagger.io" },
  { name: "Apollo GraphQL", categories: ["API"], description: "GraphQL client and server libraries for building data graphs", url: "https://apollographql.com" },
  { name: "Postman", categories: ["API", "Testing"], description: "API development and testing platform", url: "https://postman.com" },
  { name: "Google Analytics", categories: ["Analytics"], description: "Web traffic and user behavior analytics by Google", url: "https://analytics.google.com" },
  { name: "Mixpanel", categories: ["Analytics"], description: "Product analytics platform focused on event tracking", url: "https://mixpanel.com" },
  { name: "PostHog", categories: ["Analytics", "Personalisation"], description: "Open-source product analytics with feature flags and session replay", url: "https://posthog.com" },
  { name: "Amplitude", categories: ["Analytics"], description: "Product analytics platform for tracking user behavior", url: "https://amplitude.com" },
  { name: "Plausible", categories: ["Analytics"], description: "Lightweight, privacy-focused open-source web analytics", url: "https://plausible.io" },
  { name: "Hotjar", categories: ["Analytics", "Personalisation"], description: "Heatmaps, session recordings, and user feedback tool", url: "https://hotjar.com" },
  { name: "Auth0", categories: ["Authentication", "Security"], description: "Identity platform for authentication and authorization", url: "https://auth0.com" },
  { name: "Clerk", categories: ["Authentication"], description: "Drop-in authentication and user management for web apps", url: "https://clerk.com" },
  { name: "Firebase Auth", categories: ["Authentication"], description: "Authentication service by Google with multiple sign-in providers", url: "https://firebase.google.com/docs/auth" },
  { name: "Okta", categories: ["Authentication", "Security"], description: "Enterprise identity and access management platform", url: "https://okta.com" },
  { name: "Stripe", categories: ["Payment", "API"], description: "Payment processing platform for internet businesses", url: "https://stripe.com" },
  { name: "PayPal", categories: ["Payment"], description: "Online payment platform for consumers and merchants", url: "https://paypal.com" },
  { name: "Square", categories: ["Payment", "Ecommerce"], description: "Payment processing and point-of-sale platform", url: "https://squareup.com" },
  { name: "Adyen", categories: ["Payment"], description: "Global payment platform for enterprise businesses", url: "https://adyen.com" },
  { name: "Datadog", categories: ["Monitoring", "Analytics"], description: "Cloud-scale monitoring, APM, and log management platform", url: "https://datadoghq.com" },
  { name: "New Relic", categories: ["Monitoring", "Analytics"], description: "Full-stack observability and application performance monitoring", url: "https://newrelic.com" },
  { name: "Sentry", categories: ["Monitoring"], description: "Application error tracking and performance monitoring", url: "https://sentry.io" },
  { name: "Grafana", categories: ["Monitoring", "Analytics"], description: "Open-source dashboarding and visualization for metrics", url: "https://grafana.com" },
  { name: "Prometheus", categories: ["Monitoring"], description: "Open-source time-series metrics and alerting system", url: "https://prometheus.io" },
  { name: "PagerDuty", categories: ["Monitoring"], description: "Incident management and on-call alerting platform", url: "https://pagerduty.com" },
  { name: "Resend", categories: ["Email", "API"], description: "Developer-first transactional email API", url: "https://resend.com" },
  { name: "SendGrid", categories: ["Email", "API"], description: "Cloud-based email delivery and marketing platform", url: "https://sendgrid.com" },
  { name: "Mailgun", categories: ["Email", "API"], description: "Transactional email API service for developers", url: "https://mailgun.com" },
  { name: "Amazon SES", categories: ["Email", "API"], description: "Scalable email sending service by AWS", url: "https://aws.amazon.com/ses/" },
  { name: "Cloudinary", categories: ["Image / Media", "CDN"], description: "Cloud-based image and video management and transformation", url: "https://cloudinary.com" },
  { name: "imgix", categories: ["Image / Media", "CDN"], description: "Real-time image processing and CDN delivery", url: "https://imgix.com" },
  { name: "Mux", categories: ["Image / Media", "API"], description: "Video streaming and analytics API platform", url: "https://mux.com" },
  { name: "UploadThing", categories: ["Image / Media", "API"], description: "File upload service designed for TypeScript web apps", url: "https://uploadthing.com" },
  { name: "Jest", categories: ["Testing"], description: "JavaScript testing framework with built-in mocking and assertions", url: "https://jestjs.io" },
  { name: "Vitest", categories: ["Testing"], description: "Fast Vite-native unit testing framework", url: "https://vitest.dev" },
  { name: "Playwright", categories: ["Testing"], description: "Cross-browser end-to-end testing framework by Microsoft", url: "https://playwright.dev" },
  { name: "Cypress", categories: ["Testing"], description: "End-to-end testing framework for web applications", url: "https://cypress.io" },
  { name: "Testing Library", categories: ["Testing"], description: "DOM testing utilities encouraging accessible query patterns", url: "https://testing-library.com" },
  { name: "Selenium", categories: ["Testing"], description: "Browser automation framework for web application testing", url: "https://selenium.dev" },
  { name: "Storybook", categories: ["Testing", "Design"], description: "UI component development and visual testing workshop", url: "https://storybook.js.org" },
  { name: "GitHub Actions", categories: ["CI/CD"], description: "Workflow automation and CI/CD built into GitHub", url: "https://github.com/features/actions" },
  { name: "CircleCI", categories: ["CI/CD"], description: "Cloud-based continuous integration and delivery platform", url: "https://circleci.com" },
  { name: "Jenkins", categories: ["CI/CD"], description: "Open-source automation server for building CI/CD pipelines", url: "https://jenkins.io" },
  { name: "Terraform", categories: ["CI/CD", "Hosting"], description: "Infrastructure-as-code tool for provisioning cloud resources", url: "https://terraform.io" },
  { name: "Pulumi", categories: ["CI/CD", "Hosting"], description: "Infrastructure-as-code using general-purpose programming languages", url: "https://pulumi.com" },
  { name: "Figma", categories: ["Design", "Collaboration"], description: "Browser-based collaborative UI design and prototyping tool", url: "https://figma.com" },
  { name: "Sketch", categories: ["Design"], description: "macOS vector design tool for UI and icon design", url: "https://sketch.com" },
  { name: "Adobe XD", categories: ["Design"], description: "UI/UX design and prototyping tool by Adobe", url: "https://adobe.com/products/xd.html" },
  { name: "Framer", categories: ["Design", "Hosting"], description: "Interactive design tool with production website publishing", url: "https://framer.com" },
  { name: "Canva", categories: ["Design"], description: "Online graphic design tool for non-designers", url: "https://canva.com" },
  { name: "InVision", categories: ["Design", "Collaboration"], description: "Digital product design and prototyping platform", url: "https://invisionapp.com" },
  { name: "Vite", categories: ["Build Tools"], description: "Fast frontend build tool with hot module replacement", url: "https://vite.dev" },
  { name: "Webpack", categories: ["Build Tools"], description: "Module bundler for JavaScript applications", url: "https://webpack.js.org" },
  { name: "esbuild", categories: ["Build Tools"], description: "Extremely fast JavaScript and TypeScript bundler written in Go", url: "https://esbuild.github.io" },
  { name: "Turborepo", categories: ["Build Tools"], description: "High-performance monorepo build system by Vercel", url: "https://turbo.build" },
  { name: "Nx", categories: ["Build Tools"], description: "Monorepo build system with dependency-aware task orchestration", url: "https://nx.dev" },
  { name: "Bun", categories: ["Build Tools", "Language"], description: "All-in-one JavaScript runtime, bundler, and package manager", url: "https://bun.sh" },
  { name: "Deno", categories: ["Language", "Build Tools"], description: "Secure JavaScript/TypeScript runtime with built-in tooling", url: "https://deno.com" },
  { name: "Node.js", categories: ["Language"], description: "Server-side JavaScript runtime built on V8", url: "https://nodejs.org" },
  { name: "pnpm", categories: ["Build Tools"], description: "Fast, disk-efficient JavaScript package manager", url: "https://pnpm.io" },
  { name: "Slack", categories: ["Collaboration"], description: "Team messaging and communication platform", url: "https://slack.com" },
  { name: "Notion", categories: ["Collaboration"], description: "All-in-one workspace for docs, wikis, and project management", url: "https://notion.so" },
  { name: "Linear", categories: ["Collaboration"], description: "Streamlined issue tracking and project management for dev teams", url: "https://linear.app" },
  { name: "Jira", categories: ["Collaboration"], description: "Issue tracking and agile project management by Atlassian", url: "https://atlassian.com/software/jira" },
  { name: "Confluence", categories: ["Collaboration"], description: "Team wiki and documentation platform by Atlassian", url: "https://atlassian.com/software/confluence" },
  { name: "Discord", categories: ["Collaboration"], description: "Voice, video, and text communication platform", url: "https://discord.com" },
  { name: "Microsoft Teams", categories: ["Collaboration"], description: "Team communication and collaboration hub by Microsoft", url: "https://microsoft.com/en-us/microsoft-teams" },
]

async function main() {
  const sql = neon(process.env.DATABASE_URL!)
  let updated = 0

  for (const t of DATA) {
    const result = await sql`
      UPDATE brands SET
        categories = ${t.categories},
        category = ${t.categories[0]},
        description = ${t.description},
        url = ${t.url}
      WHERE name = ${t.name}
      RETURNING id
    `
    if (result.length) updated++
  }

  // Stats
  const [{ total }] = await sql`SELECT COUNT(*)::int as total FROM brands`
  const [{ with_desc }] = await sql`SELECT COUNT(*)::int as with_desc FROM brands WHERE description != '' AND description IS NOT NULL`
  const [{ with_url }] = await sql`SELECT COUNT(*)::int as with_url FROM brands WHERE url != '' AND url IS NOT NULL`

  console.log(`✓ Updated ${updated} technologies`)
  console.log(`  Total: ${total}, With description: ${with_desc}, With URL: ${with_url}`)
}

main().catch(e => { console.error('Failed:', e.message); process.exit(1) })
